default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_IP"] %>
  pool: 800
  timeout: 5000

development:
  fidelizedb:
    <<: *default
    database: fidelizedb_development
    port: 5432

test:
  fidelizedb:
    <<: *default
    database: fidelizedb_test

production: &production
  fidelizedb:
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
    host: <%= ENV["DATABASE_IP"] %>
    pool: 1000

qa: 
  <<: *production